### ISSUE TITLE
This is so cool!

### ISSUE THREAD

**Issue by vsoch** [MillionConcepts/software_project_management#1]
hey @cmillion ! I love this! Is there an opportunity to make some kind of template, either a web interface you can export from or even just a template repository with a simple set of sections that pretty render into a project document on pages. It could even be a combination of that and then pre=populated Google sheets, etc. We could make it as a project in https://github.com/rseng if you are interested. Thoughts?

**Comment by cmillion** [comment]
Thanks! I'm in favor of any derived work that you want to make, but I don't have the bandwidth to help with it. Another thing that I've thought would be useful is a simplified ConOps template maybe formatted similarly to a "startup canvas."

**Comment by vsoch** [comment]
What is ConOps?

**Comment by cmillion** [comment]
"Concept of Operations" --- one of the things explained [in the text](https://github.com/MillionConcepts/software_project_management/blob/main/practical_software_estimation/a_practical_guide_to_research_software_project_estimation.pdf).
